[package]
name = "rivet_gui_shared"
version = "0.1.0"
edition.workspace = true
license.workspace = true

[dependencies]
serde = { version = "1.0.228", features = ["derive"] }
uuid = { version = "1.21.0", features = ["v4", "serde", "js"] }
